/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scpaa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ar-mo
 */
public class RegistrarActividad extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarActividad
     */
    public RegistrarActividad() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    void RegistrarNuevaActividad()
    {
        txtTipo = (String)TipoActividad.getSelectedItem();
        txtAnio  = (String)AñoActividad.getSelectedItem();
        txtPeriodo = (String)PeriodoActividad.getSelectedItem();
        
        if(txtNombre.getText().isEmpty() || txtLugar.getText().isEmpty() ||txtTipo.equals(Vacio) || txtAnio.equals(Vacio) || txtPeriodo.equals(Vacio))
        {
            JOptionPane.showMessageDialog(this, "Hay campos vacios o no eligio alguna opción");
        }

        else
        {
            int Guardar = JOptionPane.showConfirmDialog(null, "Desea registrar la nueva actividad?");

            if(Guardar == 0)
            {
                try
                {
                    PreparedStatement pst = cn.prepareStatement("INSERT INTO actividad (NombreActividad,LugarActividad,PeriodoActividad,AnioActividad,TipoActividad,IDActividad) VALUES (?,?,?,?,?,NULL)");

                    pst.setString(1, txtNombre.getText());
                    pst.setString(2, txtLugar.getText());
                    pst.setString(3, txtPeriodo);
                    pst.setString(4, txtAnio);
                    pst.setString(5, txtTipo);

                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Datos Guardados...");

                    MenuPrincipal Regresar = new MenuPrincipal();
                    Regresar.setVisible(true);
                    dispose();
                }

                catch (SQLException e)
                {
                    
                    JOptionPane.showMessageDialog(this, "Ha Ocurrido Un Error");
                    System.out.println(e);
                }
            }

            else
            {
                JOptionPane.showMessageDialog(this, "Operación Cancelada");
            }
        }        
    }
    
    void Salir()
    {
        int Salir = JOptionPane.showConfirmDialog(null, "¿Desea salir del programa?");
        
        if(Salir == 0)
        {
            System.exit(0);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Operación cancelada");
        }
    }
    
    void Regresar()
    {
        Volver = JOptionPane.showConfirmDialog(null, "¿Desea regresar al menú principal?");
        
        if(Volver == 0)
        {
            MenuPrincipal Regresar = new MenuPrincipal();
            Regresar.setVisible(true);
            dispose();
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Operación cancelada...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        Periodo = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtLugar = new javax.swing.JTextField();
        Año = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        TipoActividad = new javax.swing.JComboBox();
        PeriodoActividad = new javax.swing.JComboBox();
        AñoActividad = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Nombre.setText("NOMBRE:");

        Lugar.setText("LUGAR:");

        Periodo.setText("PERIODO:");

        Tipo.setText("TIPO:");

        Registrar.setText("REGISTRAR");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        Año.setText("AÑO:");

        Titulo.setText("REGISTRO DE NUEVA ACTIVIDAD");

        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Regresar.setText("REGRESAR");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        TipoActividad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELIJA UNA OPCIÓN", "Actividad deportiva, civica o cultural", "Actividad de investigacion e innovacion" }));
        TipoActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActividadActionPerformed(evt);
            }
        });

        PeriodoActividad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELIJA UNA OPCIÓN", "Enero - Julio", "Agosto - Diciembre" }));

        AñoActividad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELIJA UNA OPCIÓN", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Regresar)
                .addGap(102, 102, 102)
                .addComponent(Registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tipo)
                    .addComponent(Periodo)
                    .addComponent(Lugar)
                    .addComponent(Nombre)
                    .addComponent(Año))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TipoActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PeriodoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre)
                    .addComponent(txtLugar))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lugar)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Periodo)
                    .addComponent(PeriodoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Año)
                    .addComponent(AñoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo)
                    .addComponent(TipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(Regresar)
                    .addComponent(Registrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        RegistrarNuevaActividad();
    }//GEN-LAST:event_RegistrarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Salir();
    }//GEN-LAST:event_SalirActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Regresar();
    }//GEN-LAST:event_RegresarActionPerformed

    private void TipoActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActividadActionPerformed
        
    }//GEN-LAST:event_TipoActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Año;
    private javax.swing.JComboBox AñoActividad;
    private javax.swing.JLabel Lugar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Periodo;
    private javax.swing.JComboBox PeriodoActividad;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Tipo;
    private javax.swing.JComboBox TipoActividad;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
Conectar cc= new Conectar();
Connection cn= cc.conexion();
String txtTipo, txtAnio, txtPeriodo, Vacio = "ELIJA UNA OPCIÓN";
int Volver;
}
